### PR TITLE
[FEATURE] Added script for setting additional TYPO3 base variants

### LINKED ISSUE #2: project_name variable and site configuration
When setting up a new project and defining a unique PROJECT_NAME, is it possible to automate so Site Configuration is updated in the process?

`/config/sites/t3kit/config.yaml`
```
baseVariants:
  -
    base: `'http://new-site.local'
```

### PR DESCRIPTION
**Pull request by mabolek**
Fixes #2

### CODE REVIEW

**Comment by dmh** [comment]
Hey,
I am wondering how to automate this, to not do it manually on through Composer. 
What if to add it to `up.sh` file and modify it base on `COMPOSE_PROJECT_NAME` variable?

**Comment by dmh** [comment]
https://github.com/t3kit/t3kit-starter/issues/2

**Comment by mabolek** [comment]
@dmh I'm looking at this again.

> I am wondering how to automate this, to not do it manually on through Composer.
> What if to add it to `up.sh` file and modify it base on `COMPOSE_PROJECT_NAME` variable?

You can hook in the script where ever you wish. So, you can run `addbasevariant.sh {$COMPOSE_PROJECT_NAME.blah.blah}` to `up.sh` if you wish.

With that I mean that I wouldn't put the entire script into `up.sh`, just call it from there. Calling it manually would still make a lot of sense if you need to add another domain manually. Better than editing the site manually.

**Comment by dmh** [comment]
check this one, it works as it is, and without additional scripts
https://github.com/t3kit/t3kit-starter/blob/master/config/sites/t3kit/config.yaml#L4

**Comment by mabolek** [comment]
@dmh Aha! I agree. That is a better solution. I'll update the other PR to reflect this. Closing.

**Pull request closed without merging**
